import os
import time
import numpy as np
import pandas as pd

def readCSV():
    # Read accelerometer data
    file_path = 'motorSync.csv'
    data = []
    data = pd.DataFrame(data)

    # Check if file exists
    for i in range(5):
        time.sleep(0.1)
        file_name = [f for f in os.listdir('/tmp') if f.endswith('motorSync.csv')]
        if file_name:
            file_path = '/tmp/' + file_name[0]
            break

    # Read and delete the processed CSV file
    if os.path.isfile(file_path):
        data = pd.read_csv(file_path)
        os.remove(file_path)
    else:
    # Error check
        print("/tmp/*motorSync.csv was not generated by ACCELEROMETER_MEASURE.")

    return data

def get_noise():
    # Load measurements
    data = readCSV()

    # Determine average to remove noise
    if not data.empty:
        avg_x = float(np.average(data['accel_x']))
        avg_y = float(np.average(data['accel_y']))
        avg_z = float(np.average(data['accel_z']))
    else:
        avg_x = 1
        avg_y = 1
        avg_z = 1

    return (avg_x, avg_y, avg_z)
